### ISSUE TITLE
Text link not clickable. 

### ISSUE THREAD

**Issue by jarodise** [raghuveerdotnet/simply-jekyll#1]
Hi, thanks for creating such a great theme. While browsing the template, I encountered something that seems to be a bug, that is, the "text part" of the navigation link is not clickable, for example "<-Home" , the text " Home" is not clickable, even thought when you hover over it , it indicates that it is clickable, but when you click on it , nothing really happens, so I think it might be a bit misleading.

**Comment by raghuveerdotnet** [comment]
Hi Jarodise, Thank you for the kind words. Glad that you liked it. 

The issue has been fixed with the latest commit.  :)
