### ISSUE TITLE
How can I add a new category in addition to About, Tags, and RSS?

### ISSUE THREAD

**Issue by classicrob** [raghuveerdotnet/simply-jekyll#14]
Hi! I'd like to add a category, "Work with Me" to the site header. How would I do that and pick an icon?

![image](https://user-images.githubusercontent.com/46608303/91107520-b81ec900-e632-11ea-8943-66faedcafb4d.png)

**Comment by raghuveerdotnet** [comment]
Please see the image below for reference. And to style the tab further, go to `style.css` and look for relevant classes, for eg. For categories div, the class name is `categories`, and categories icon it is `icon-category`. If you want to stylize your tab, you will have to add it there.
![rob_category](https://user-images.githubusercontent.com/24671386/91184754-97c23d80-e70a-11ea-8752-43b63830e3df.png)

**Comment by classicrob** [comment]
Thank you!
