### ISSUE TITLE
Possible to delete the posts and show only notes feed on the front page?

### ISSUE THREAD

**Issue by jarodise** [raghuveerdotnet/simply-jekyll#3]
Hi! I find having both posts and notes a bit confusing, since I only want to use this to build a digital garden, so simply having notes would be enough, is there a way I can delete the posts part and showcase only the notes? unfortunately, I'm not tech savvy enough the tweak the layout structure myself, please kindly advise. 

and thanks again for making such a great project! .

**Comment by raghuveerdotnet** [comment]
Hi Jarodise,

Just search through the entire project and delete all the existing blocks of statements containing `site.notes`. And then replace all the blocks of statements containing `site.posts` with `site.notes`.  Once you do that just delete the posts directory. I think that should be sufficient.

**Comment by jarodise** [comment]
Ha, that sounds like a sure way to break the site, I don't think without proper tech background I'm able to to pull something like that off, thanks anyway.

**Comment by raghuveerdotnet** [comment]
Hi Jarodise,

You can take a look at Rob Haisfield's(@classicrob) fork of this theme(https://github.com/classicrob/simply-jekyll). He has done just what you asked for. Try forking Rob's repo of simply-jekyll and let me know if that works for you. :)
