### ISSUE TITLE
Suggestion: Add information on Related Posts section

### ISSUE THREAD

**Issue by saurabhkarmakar** [raghuveerdotnet/simply-jekyll#4]
It took me some time to understand the difference between *Linked References* and *Related Posts*. 
- *Linked References* are backlinks. In a topic, the *Linked References* section will list all other topics that have internal links to it. 
- *Related Posts* section in a topic lists all other topics that share the same tag(s) with it.
The neat stuff is, if a topic has already appeared in the Linked References section, it will not appear again in the *Related Posts* section. 
I suggest you add the information about Related Posts in the *Exploring the features of Simply Jekyll*.

**Comment by raghuveerdotnet** [comment]
Hi saurabhkarmakar,

Thanks for the suggestion, I have incorporated your suggestion to the _[Exploring the features of Simply Jekyll](https://simply-jekyll.netlify.app/posts/exploring-the-features-of-simply-jekyll)_ Page.
