### ISSUE TITLE
Support for using other Markdown editors when authoring content for simply-jekyll

### ISSUE THREAD

**Issue by saurabhkarmakar** [raghuveerdotnet/simply-jekyll#5]
Hi Raghuveer,
I love the theme. However, the sytax used for the custom features makes it difficult to author documents in other markdown editors that support wiki-style links (double square brackets) with auto-suggestion (example: Bear, Obsidian, Zettlr, etc). So, somebody who is planning to use your theme will get restricted to authoring using VS Code along with your Notecomplete plugin.

Let me explain the issue with an example. Say, I am authoring a note using Bear app on Mac. And to highlight a snippet of text I write [[This is important::highlight]]. Bear supports wiki-style links using double square brackets. If I click the text within the double brackets, it will imeediately create a new topic with the title *This is important::highlight*. Same will happen with Obsidian and Zettlr.

By keeping the wiki-style link custom syntax but altering the syntax you are using for other custom features, the limitation of usable markdown editors will be removed and more people will enjoy using your theme.

I have few suggestions regarding the alternate syntax that may be used for custom formatting in your theme:
1. External links: No need to change. You already support all markdown link formats for external links. So, people can use them.
2. Side note/Margin note/Flash card/Partial transclusion: You can either use some other style of brackets or use the footnotes style that many markdown editor supports. I recommend the latter. For example, where the person wants to insert a side note or margin note, he types `[^1::lsn]` and then enters `[^1::lsn] This is left side note` in the very next paragraph or anywhere else in the topic. You will render this as a side note or margin note while the other editors will show it as footnotes. For partial transclusion, he types `[^2::lsn-transclude]` where he wants the transclusion to appear. And then he types `[^2::lsn-transclude] [[This is the topic for partial transclusion]]` anywhere else in the topic. More information on footnotes syntax is available at https://www.markdownguide.org/extended-syntax/
3. Highlight: I use Obsidian. In that, they enclose the text to be highlighted using two equal signs on both sides. Example `==this is important==`. You may adopt it.
4. Wrapping Text: Perhaps another style of bracket or a variation of the fenced code block syntax. For example: 
```
```::wrap
The is the wrapped text paragraph.
/```
```

**Comment by raghuveerdotnet** [comment]
Hi Saurabh, 

Thanks for the suggestions, these are really well thought out. I would be happy if you or anyone interested could implement this and create a pull request as I am held up with some important work-related things and might not be able to spend time on this for the next couple of months or so unless it is a trivial fix. 

**†** As for the editors, I have a feeling that doing anything editor specific with the theme is not a good idea. Editors are supposed to enforce design constraints of the language they support, not introduce their own design constraints(syntax in this case); that is why I chose to go with vim/vscode/sublime --- extensible and independent as editors should be.

**Comment by saurabhkarmakar** [comment]
Hi Raghuveer. Thanks for considering my suggestions. I understand to your view on using editors to enforce design constraints. I am tech novice, but will try to get some of my techie friends interested in contributing to your project. This is a wonderful theme you have made.

[Saurabh - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=kyb77)	[kyb77]

On July 4, 2020 at 15:18 GMT, Raghuveer S <notifications@github.com> wrote:

Hi Saurabh,

Thanks for the suggestions, these are really well thought out. I would be happy if you or anyone interested could implement this and create a pull request as I am held up with some important work-related things and might not be able to spend time on this for the next couple of months or so unless it is a trivial fix.

† As for the editors, I have a feeling that doing anything editor specific with the theme is not a good idea. Editors are supposed to enforce design constraints of the language they support, not introduce their own design constraints(syntax in this case); that is why I chose to go with vim/vscode/sublime --- extensible and independent as editors should be.
