### ISSUE TITLE
Possible to make the theme's links understand baseurls and a folder structure?

### ISSUE THREAD

**Issue by ryan-p-randall** [raghuveerdotnet/simply-jekyll#9]
I really like this theme—thank you so much for making and sharing it! I've been trying to adapt it to work within my existing GitHub Pages site, without using Netlify. 

I'd like to have all my posts, notes, backlinks, etc work with a baseurl or folder on my existing site, something like: `siteurl.tld/wiki/`. I've gotten far enough to have my adaptation [output notes with a baseurl](https://www.ryanpatrickrandall.com/wonky-wiki/notes/Comparison-based-on-accomplishment-does-not-have-a-baseline). But I've hit the limit of how well I know Liquid programming, so the links from the index and other things don't point to the full url. They skip the baseurl I'm using.

Is that a feature that could be added to the code of your theme?

My ideal structure would be a blend of your theme's features and [Tom Critchlow's folder-based digital garden structure](https://tomcritchlow.com/2019/02/17/building-digital-garden/). So I'm curious if there's a way to use add your theme's related posts, backlinks, and double bracket link syntax to a wiki that uses multiple folders rather than organizing primarily by tags.

**Comment by raghuveerdotnet** [comment]
Hi Ryan,

Adding baseurl has nothing to do with the theme, all you have to do is add `{{ site.url }}{{ site.baseurl }}` everywhere you have hrefs.

**Comment by raghuveerdotnet** [comment]
[simply-jekyll.zip](https://github.com/raghuveerdotnet/simply-jekyll/files/4964442/simply-jekyll.zip)
Here is  a modified version of simply jekyll with `{{ site.url }}{{ site.baseurl }}`. Works just fine. (Just download the zip and try it. You should see that the base url has been changed to `/blog`. All I did was add a baseurl called `/blog` in config.yml and replaced all the hrefs with `{{ site.url }}{{ site.baseurl }}`.

The reason I haven't added it to the main repo is most people use relative url, and it becomes a headache to write `{{ site.url }}{{ site.baseurl }}` before you include an image etc.
